### PR TITLE
First draft for B501

### PR DESCRIPTION
**Pull request by egonw**

### CODE REVIEW

**Comment by larsgw** [comment]
(`(s.s.)` here means sensu stricto so the subgenus would be the same as the respective genus)

**Comment by egonw** [comment]
> (`(s.s.)` here means sensu stricto so the subgenus would be the same as the respective genus)

Yeah, I did not remember what you said. I looked at the other files, but it was too hot to see how to do it.

**Comment by larsgw** [comment]
To generate the DwC:

```
cd tools/resources
npm install
node .
node make-index.js
```

**Comment by larsgw** [comment]
Please rebase and retry?

**Comment by egonw** [comment]
@larsgw, okay, how about now?

I noticed that the indices are not sorted, so it's hard to see what actually changed, and what just moved around.

**Comment by larsgw** [comment]
The dwc file is still missing, I'm not sure why.

> I noticed that the indices are not sorted, so it's hard to see what actually changed, and what just moved around.

Yeah I see that now.

**Comment by egonw** [comment]
> The dwc file is still missing, I'm not sure why.

Because I did not know I had to add that one too. Adding it now.

**Comment by egonw** [comment]
Checks fail because of https://github.com/identification-resources/catalog/pull/44

**Pull request merged**
