### PR TITLE
B1004 and B1005 indices

### PR DESCRIPTION
**Pull request by egonw**
I can make the index after the other PR is merged, since the index is changed all over the place.

### CODE REVIEW

**Comment by egonw** [comment]
@larsgw, consider this one "work in progress"; I just noted B1005 is basically the same book and just a different edition. So, I'll add that one too.

**Comment by egonw** [comment]
Checks fail because of https://github.com/identification-resources/catalog/pull/44

**Comment by egonw** [comment]
Differences between B1004 and B1005:

```diff
--- ../../resources/txt/B1004.txt       2022-08-23 09:21:41.375780823 +0200
+++ ../../resources/txt/B1005.txt       2022-08-23 09:34:22.693991619 +0200
@@ -27,18 +27,20 @@
     sylvarum (Linnaeus 1761)
     veteranus (Fabricius 1793)
   Psithyrus
+    barbutellus (Kirby 1802)
     bohemicus Seidl 1837
-    compestris (Panzer 1801)
+    campestris (Panzer 1801)
     flavidus (Eversmann 1852)
+    maxillosus Klug 1817
     norvegicus (Sparre Schneider 1918)
     quadricolor (Lepeletier 1832)
     rupestris (Fabricius 1793)
     sylvestris (Lepeletier 1832)
     vestalis (Geoffroy 1785)
   Bombias
-    confusus Schenck 1859
+    confusus Schenck 1861
   Bombus
-    cryptarum (Fabricius 1775)
+    cryptarum Fabricius 1775
     lucorum (Linnaeus 1761)
     magnus (Vogt 1911)
     terrestris (Linnaeus 1758)
@@ -46,16 +48,15 @@
     cullumanus (Kirby 1802)
     semenoviellus Skorikov 1910
   Subterraneobombus
-    distingeundus Morawitz 1869
     fragrans (Pallas 1771)
     subterraneus (Linnaeus 1758)
   Pyrobombus
-    heamaturus Kriechbaumer 1870
+    haematurus Kriechbaumer 1870
     hypnorum (Linnaeus 1758)
     jonellus (Kirby 1802)
     monticola Smith 1849
     pratorum (Linnaeus 1761)
-    pyraneus (Pérez 1879)
+    pyranaeus (Pérez 1879)
   Melanobombus
     lapidarius (Linnaeus 1758)
     sichelii Radoszkowski 1859
```

**Comment by larsgw** [comment]
In the case of _Bombus (Psithyrus) compestris_ (Panzer 1801) GNVerifier performs a fuzzy match. I could reject those (as I did before) so that exact matches are required.

**Pull request merged**
